import { createHmac, timingSafeEqual } from "node:crypto";
import { Hono } from "hono";
import { cors } from "hono/cors";
import { z } from "zod";
import { analyzeWebsite, discoverPublicProspects, generateCandidates } from "../../../packages/enrichment/src/index.js";
import { createSender, normalizeSmartleadEvent, type SenderPort } from "../../../packages/sending/src/index.js";
import { LIMITS, redactReply } from "../../../packages/shared/src/index.js";
import { MemoryStore, type Campaign, type Org } from "./store.js";

type Vars = { org: Org };
const jsonError = (c: { json: Function }, status: number, code: string, message: string) => c.json({ error: { code, message } }, status as never);
const ownedSchema = z.object({ firstName: z.string().min(1), lastName: z.string().min(1), domain: z.string().min(3), knownEmail: z.string().email().optional() });
const campaignSchema = z.object({ name: z.string().min(1), sequence: z.array(z.object({ subject: z.string().min(1), body: z.string().min(1), delayDays: z.number().int().nonnegative() })).min(1).optional() });
class ApiFailure extends Error { constructor(readonly status: number, readonly code: string, message: string) { super(message); } }

export function createApp(options: { store?: MemoryStore; sender?: SenderPort; fetcher?: typeof fetch } = {}) {
  const store = options.store ?? new MemoryStore(), sender = options.sender ?? createSender(), fetcher = options.fetcher ?? fetch;
  const app = new Hono<{ Variables: Vars }>(); app.use("*", cors({ origin: process.env.WEB_BASE_URL ?? "http://localhost:3000" }));
  app.get("/health", async (c) => c.json({ ok: true, sender: await sender.health() }));
  app.get("/v1/openapi.json", (c) => c.json(openapi));
  app.post("/v1/internal/bootstrap", async (c) => { if ((process.env.INTERNAL_SECRET ?? "change-me") !== c.req.header("x-internal-secret")) return jsonError(c, 401, "unauthorized", "Invalid internal secret"); const body = await c.req.json().catch(() => ({})) as { name?: string; plan?: "free" | "pro" }; return c.json(store.bootstrap(body.name, body.plan)); });
  app.use("/v1/*", async (c, next) => { if (c.req.path === "/v1/prospects/discover" || c.req.path.startsWith("/v1/webhooks/") || c.req.path.startsWith("/v1/internal/")) return next(); const auth = c.req.header("authorization")?.replace(/^Bearer\s+/i, "") ?? ""; const org = store.orgForKey(auth); if (!org) return jsonError(c, 401, "invalid_api_key", "A valid Replo API key is required"); c.set("org", org); await next(); });
  app.get("/v1/me", (c) => c.json({ organization: c.get("org") }));
  app.post("/v1/research/from-url", async (c) => { const org = c.get("org"), body = z.object({ url: z.string().url() }).parse(await c.req.json()); const product = await analyzeWebsite(body.url, fetcher); const result = { product, icp: [{ title: product.keywords.slice(0, 3).join(" · ") || "B2B teams", description: `Organizations whose public positioning overlaps with ${product.summary.slice(0, 140)}` }], angles: [{ title: `Why ${product.name}`, body: product.summary }] }; return c.json({ jobId: store.createJob(org.id, "research", result).id }); });
  app.get("/v1/prospects/discover", async (c) => { const input = z.object({ url: z.string().url(), audience: z.string().max(180).optional(), territory: z.string().max(80).optional(), limit: z.coerce.number().int().min(1).max(30).optional() }).parse(c.req.query()); return c.json(await discoverPublicProspects({ url: input.url!, audience: input.audience, territory: input.territory, limit: input.limit }, fetcher)); });
  app.get("/v1/jobs/:id", (c) => { const row = store.jobs.get(c.req.param("id")); if (!row || row.orgId !== c.get("org").id) return jsonError(c, 404, "not_found", "Job not found"); return c.json(row); });
  app.post("/v1/emails/find", async (c) => { const org = c.get("org"), input = ownedSchema.parse(await c.req.json()); if (org.plan === "free" && org.monthlyResolveCount >= 30) return jsonError(c, 429, "resolve_quota", "Free monthly resolve quota reached"); const candidates = generateCandidates({ firstName: input.firstName!, lastName: input.lastName!, domain: input.domain!, knownEmail: input.knownEmail }); org.monthlyResolveCount++; const candidate = candidates.find((x) => x.confidence >= LIMITS.minConfidence) ?? null; return c.json({ result: candidate ? "resolved" : "not_found", candidate }); });
  app.post("/v1/emails/verify", async (c) => { const body = z.object({ email: z.string().email() }).parse(await c.req.json()); const domain = body.email.split("@")[1]; return c.json({ email: body.email, status: domain ? "risky" : "invalid", method: "syntax_dns_heuristic" }); });
  app.post("/v1/messages/generate", async (c) => { const body = z.object({ firstName: z.string().default("there"), companyName: z.string().default("your company"), angle: z.string().default("pipeline") }).parse(await c.req.json()); return c.json({ steps: [{ subject: `Idea for ${body.companyName}`, body: `Hi ${body.firstName},\n\nI noticed ${body.companyName} and had a practical idea around ${body.angle}. Open to a quick exchange?\n\nIf this isn't relevant, reply unsubscribe.`, delayDays: 0 }, { subject: `Re: Idea for ${body.companyName}`, body: `Hi ${body.firstName},\n\nWorth a look, or should I close the loop?`, delayDays: 3 }] }); });
  app.post("/v1/campaigns", async (c) => { const input = campaignSchema.parse(await c.req.json()); return c.json(store.createCampaign(c.get("org").id, { name: input.name!, sequence: input.sequence?.map((x) => ({ subject: x.subject!, body: x.body!, delayDays: x.delayDays! })) }), 201); });
  app.post("/v1/campaigns/:id/leads", async (c) => { const campaign = ownCampaign(store, c.get("org"), c.req.param("id")); if (!campaign) return jsonError(c, 404, "not_found", "Campaign not found"); const body = z.object({ leads: z.array(ownedSchema.extend({ companyName: z.string().optional() })).min(1) }).parse(await c.req.json()); campaign.leads.push(...body.leads.map((x) => ({ id: crypto.randomUUID(), firstName: x.firstName!, lastName: x.lastName!, domain: x.domain!, companyName: x.companyName, verification: x.knownEmail ? "valid" : "pending", email: x.knownEmail, confidence: x.knownEmail ? 0.99 : undefined }))); return c.json({ added: body.leads.length }); });
  app.post("/v1/campaigns/:id/resolve", async (c) => { const org = c.get("org"), campaign = ownCampaign(store, org, c.req.param("id")); if (!campaign) return jsonError(c, 404, "not_found", "Campaign not found"); let resolved = 0; for (const lead of campaign.leads) if (!lead.email) { const candidate = generateCandidates(lead)[0]; if (candidate && candidate.confidence >= LIMITS.minConfidence) { lead.email = candidate.email; lead.confidence = candidate.confidence; lead.verification = candidate.verification; resolved++; } } org.monthlyResolveCount += campaign.leads.length; return c.json({ resolved, skipped: campaign.leads.length - resolved }); });
  app.post("/v1/campaigns/:id/launch", async (c) => { const org = c.get("org"), campaign = ownCampaign(store, org, c.req.param("id")); if (!campaign) return jsonError(c, 404, "not_found", "Campaign not found"); const body = await c.req.json().catch(() => ({})) as { acceptedReplyLock?: boolean }; return c.json(await launchCampaignCore(sender, org, campaign, Boolean(body.acceptedReplyLock))); });
  app.post("/v1/campaigns/launch-from-prospects", async (c) => { const org = c.get("org"), input = campaignSchema.extend({ prospects: z.array(ownedSchema.extend({ companyName: z.string().optional() })).min(1), acceptedReplyLock: z.boolean().default(false) }).parse(await c.req.json()); const campaign = store.createCampaign(org.id, { name: input.name!, sequence: input.sequence?.map((x) => ({ subject: x.subject!, body: x.body!, delayDays: x.delayDays! })) }); campaign.leads.push(...input.prospects.map((x) => ({ id: crypto.randomUUID(), firstName: x.firstName!, lastName: x.lastName!, domain: x.domain!, companyName: x.companyName, verification: x.knownEmail ? "valid" : "pending", email: x.knownEmail, confidence: x.knownEmail ? 0.99 : undefined }))); for (const lead of campaign.leads) if (!lead.email) { const candidate = generateCandidates(lead)[0]; if (candidate && candidate.confidence >= LIMITS.minConfidence) { lead.email = candidate.email; lead.confidence = candidate.confidence; lead.verification = candidate.verification; } } org.monthlyResolveCount += campaign.leads.length; return c.json(await launchCampaignCore(sender, org, campaign, input.acceptedReplyLock)); });
  app.post("/v1/campaigns/:id/pause", async (c) => { const campaign = ownCampaign(store, c.get("org"), c.req.param("id")); if (!campaign) return jsonError(c, 404, "not_found", "Campaign not found"); if (campaign.espCampaignId) await sender.pauseCampaign(campaign.espCampaignId); campaign.status = "paused"; campaign.espStatus = "PAUSED"; return c.json(campaign); });
  app.get("/v1/campaigns/:id/replies", (c) => { const org = c.get("org"), campaign = ownCampaign(store, org, c.req.param("id")); if (!campaign) return jsonError(c, 404, "not_found", "Campaign not found"); return c.json({ replies: [...store.replies.values()].filter((x) => x.campaignId === campaign.id).map((x) => redactReply(x, org.plan)) }); });
  app.get("/v1/replies/:id", (c) => { const org = c.get("org"), reply = store.replies.get(c.req.param("id")); if (!reply || reply.orgId !== org.id) return jsonError(c, 404, "not_found", "Reply not found"); return c.json(redactReply(reply, org.plan)); });
  app.post("/v1/replies/:id/draft", (c) => { const org = c.get("org"), reply = store.replies.get(c.req.param("id")); if (!reply || reply.orgId !== org.id) return jsonError(c, 404, "not_found", "Reply not found"); if (org.plan !== "pro") return jsonError(c, 402, "upgrade_required", "Pro unlocks reply drafts"); return c.json({ body: "Thanks for getting back to me. Would a short call next week work?" }); });
  app.post("/v1/replies/:id/respond", async (c) => { const org = c.get("org"), reply = store.replies.get(c.req.param("id")); if (!reply || reply.orgId !== org.id) return jsonError(c, 404, "not_found", "Reply not found"); if (org.plan !== "pro") return jsonError(c, 402, "upgrade_required", "Pro unlocks replies"); const campaign = store.campaigns.get(reply.campaignId)!; const body = z.object({ body: z.string().min(1) }).parse(await c.req.json()); return c.json(await sender.sendReply({ campaignId: campaign.espCampaignId!, threadId: reply.threadId, body: body.body })); });
  app.post("/v1/outcomes", async (c) => c.json({ accepted: true, event: await c.req.json() }, 202));
  app.get("/v1/deliverability/status", async (c) => { const org = c.get("org"), mailboxes = await sender.listMailboxes(), campaigns = [...store.campaigns.values()].filter((x) => x.orgId === org.id); const sent = campaigns.reduce((n, x) => n + x.sentCount, 0), bounces = campaigns.reduce((n, x) => n + x.bounceCount, 0); return c.json({ provider: process.env.SEND_PROVIDER ?? "mock", mailboxes, bounceRate: sent ? bounces / sent : 0, capDaily: org.plan === "free" ? LIMITS.freeDaily : LIMITS.proDaily, capMonthly: org.plan === "free" ? LIMITS.freeMonthly : null, monthlyUsed: org.monthlySendCount }); });
  app.post("/v1/webhooks/esp/smartlead", async (c) => { const raw = await c.req.text(); if (!verifyWebhook(raw, c.req.header("x-replo-webhook-secret"), c.req.query("secret"), process.env.SMARTLEAD_WEBHOOK_SECRET)) return jsonError(c, 401, "bad_signature", "Invalid webhook secret"); const payload = JSON.parse(raw) as Record<string, unknown>, event = normalizeSmartleadEvent(payload); if (store.events.has(event.eventId)) return c.json({ ok: true, duplicate: true }); store.events.add(event.eventId); const campaign = [...store.campaigns.values()].find((x) => x.espCampaignId === event.campaignId); if (!campaign) return c.json({ ok: true, ignored: "unknown_campaign" }); if (event.eventType === "sent") campaign.sentCount++; if (event.eventType === "reply") { const reply = { id: crypto.randomUUID(), orgId: campaign.orgId, campaignId: campaign.id, espReplyId: event.eventId, threadId: event.threadId ?? event.messageId ?? event.eventId, subject: event.subject ?? "Reply", bodyText: event.bodyText ?? "", fromEmail: event.fromEmail ?? event.leadEmail ?? "", fromName: event.fromName ?? null, sentiment: "neutral" }; store.replies.set(reply.id, reply); } if (event.eventType === "bounce") { campaign.bounceCount++; const rate = campaign.bounceCount / Math.max(campaign.sentCount, campaign.bounceCount); if (rate > LIMITS.maxBounceRate) { campaign.status = "paused"; campaign.pausedReason = `bounce_rate:${rate.toFixed(4)}`; if (campaign.espCampaignId) await sender.pauseCampaign(campaign.espCampaignId); } } if (event.eventType === "unsubscribe") { const lead = campaign.leads.find((x) => x.email === event.leadEmail); if (lead) lead.unsubscribed = true; } return c.json({ ok: true }); });
  app.post("/v1/webhooks/stripe", async (c) => { const payload = await c.req.json() as Record<string, any>; const orgId = payload.data?.object?.metadata?.organizationId; const org = orgId ? store.organizations.get(orgId) : undefined; if (org && ["customer.subscription.created", "customer.subscription.updated"].includes(String(payload.type)) && payload.data.object.status === "active") org.plan = "pro"; if (org && payload.type === "customer.subscription.deleted") org.plan = "free"; return c.json({ received: true }); });
  app.post("/v1/dev/simulate-reply", async (c) => { if (process.env.ALLOW_DEV_ROUTES !== "true" || (process.env.SEND_PROVIDER ?? "mock") !== "mock") return jsonError(c, 404, "not_found", "Route not available"); const org = c.get("org"), body = z.object({ campaignId: z.string(), bodyText: z.string().default("Interested"), fromEmail: z.string().email().default("owned@example.com") }).parse(await c.req.json()); const campaign = ownCampaign(store, org, body.campaignId); if (!campaign) return jsonError(c, 404, "not_found", "Campaign not found"); const reply = { id: crypto.randomUUID(), orgId: org.id, campaignId: campaign.id, espReplyId: crypto.randomUUID(), threadId: crypto.randomUUID(), subject: "Re: campaign", bodyText: body.bodyText, fromEmail: body.fromEmail, fromName: "Test recipient", sentiment: "positive" }; store.replies.set(reply.id, reply); return c.json(reply, 201); });
  app.post("/v1/dev/upgrade", (c) => { if (process.env.ALLOW_DEV_ROUTES !== "true" || process.env.BILLING_MOCK !== "true") return jsonError(c, 404, "not_found", "Route not available"); c.get("org").plan = "pro"; return c.json({ plan: "pro" }); });
  app.onError((error, c) => error instanceof z.ZodError ? jsonError(c, 400, "validation_error", error.issues.map((x) => x.message).join(", ")) : error instanceof ApiFailure ? jsonError(c, error.status, error.code, error.message) : jsonError(c, 500, "internal_error", error.message));
  return { app, store, sender };
}
function ownCampaign(store: MemoryStore, org: Org, id: string) { const row = store.campaigns.get(id); return row?.orgId === org.id ? row : undefined; }
async function launchCampaignCore(sender: SenderPort, org: Org, campaign: Campaign, acceptedReplyLock: boolean) { if (org.plan === "free" && !acceptedReplyLock) throw new ApiFailure(422, "reply_lock_consent", "Free campaigns require reply-lock disclosure acceptance"); const valid = campaign.leads.filter((x) => x.email && x.verification !== "invalid" && !x.unsubscribed); if (!valid.length || !campaign.sequence.length) throw new ApiFailure(422, "not_launchable", "At least one resolved lead and sequence step are required"); const remaining = org.plan === "free" ? LIMITS.freeMonthly - org.monthlySendCount : Number.MAX_SAFE_INTEGER; if (valid.length > remaining) throw new ApiFailure(429, "send_quota", "Monthly send quota exceeded"); const mailboxes = await sender.listMailboxes(); const configured = (process.env.SMARTLEAD_DEFAULT_EMAIL_ACCOUNT_IDS ?? "").split(",").filter(Boolean); const mailboxIds = configured.length ? configured : mailboxes.map((x) => x.id); if (!mailboxIds.length) throw new ApiFailure(503, "no_mailboxes", "No managed sending mailboxes are available"); const external = await sender.createCampaign({ name: campaign.name, dailyLimit: org.plan === "free" ? LIMITS.freeDaily : LIMITS.proDaily }); await sender.attachMailboxes(external.externalId, mailboxIds); await sender.setSequence(external.externalId, campaign.sequence); await sender.upsertLeads(external.externalId, valid.map((x) => ({ email: x.email!, firstName: x.firstName, lastName: x.lastName, companyName: x.companyName }))); await sender.startCampaign(external.externalId); Object.assign(campaign, { status: "active", espStatus: "ACTIVE", espCampaignId: external.externalId, provider: process.env.SEND_PROVIDER ?? "mock" }); org.monthlySendCount += valid.length; return { id: campaign.id, status: campaign.status, espCampaignId: campaign.espCampaignId, provider: campaign.provider }; }
function verifyWebhook(raw: string, header: string | undefined, query: string | undefined, secret: string | undefined) { if (!secret) return process.env.NODE_ENV !== "production"; const supplied = header ?? query ?? ""; if (!supplied) return false; const direct = Buffer.from(supplied), expected = Buffer.from(secret); if (direct.length === expected.length && timingSafeEqual(direct, expected)) return true; const signature = createHmac("sha256", secret).update(raw).digest("hex"), signed = Buffer.from(supplied.replace(/^sha256=/, "")), digest = Buffer.from(signature); return signed.length === digest.length && timingSafeEqual(signed, digest); }
const openapi = { openapi: "3.1.0", info: { title: "Replo API", version: "1.2.0", description: "Territory-aware public-web prospect discovery with official-company provenance and copy-ready email composition" }, servers: [{ url: "https://api.replo.eu" }], components: { securitySchemes: { bearerAuth: { type: "http", scheme: "bearer" } } }, security: [{ bearerAuth: [] }], paths: Object.fromEntries(["/health","/v1/me","/v1/research/from-url","/v1/prospects/discover","/v1/jobs/{id}","/v1/emails/find","/v1/emails/verify","/v1/messages/generate","/v1/campaigns","/v1/campaigns/launch-from-prospects","/v1/campaigns/{id}/leads","/v1/campaigns/{id}/resolve","/v1/campaigns/{id}/launch","/v1/campaigns/{id}/pause","/v1/campaigns/{id}/replies","/v1/replies/{id}","/v1/replies/{id}/draft","/v1/replies/{id}/respond","/v1/outcomes","/v1/deliverability/status","/v1/webhooks/esp/smartlead"].map((path) => [path, { get: { responses: { "200": { description: "OK" } } }, post: { responses: { "200": { description: "OK" } } } }])) };
