import { createApp } from "../apps/api/src/app.js";
process.env.INTERNAL_SECRET = "smoke"; process.env.SEND_PROVIDER = "mock"; process.env.ALLOW_DEV_ROUTES = "true"; process.env.BILLING_MOCK = "true";
const { app } = createApp();
const json = async (path: string, init: RequestInit = {}) => { const response = await app.request(path, init); const body = await response.json() as any; if (!response.ok) throw new Error(`${path}: ${response.status} ${JSON.stringify(body)}`); return body; };
const boot = await json("/v1/internal/bootstrap", { method: "POST", headers: { "x-internal-secret": "smoke", "content-type": "application/json" }, body: JSON.stringify({ name: "Smoke" }) }); const headers = { authorization: `Bearer ${boot.apiKey}`, "content-type": "application/json" };
const research = await json("/v1/research/from-url", { method: "POST", headers, body: JSON.stringify({ url: "https://replo.it" }) }); const job = await json(`/v1/jobs/${research.jobId}`, { headers }); if (job.status !== "completed") throw new Error("research did not complete");
const campaign = await json("/v1/campaigns", { method: "POST", headers, body: JSON.stringify({ name: "Smoke", sequence: [{ subject: "Safe test", body: "Hi {{first_name}}", delayDays: 0 }] }) });
await json(`/v1/campaigns/${campaign.id}/leads`, { method: "POST", headers, body: JSON.stringify({ leads: [{ firstName: "Owned", lastName: "Inbox", domain: "example.com", knownEmail: "owned@example.com" }] }) }); await json(`/v1/campaigns/${campaign.id}/resolve`, { method: "POST", headers }); const launch = await json(`/v1/campaigns/${campaign.id}/launch`, { method: "POST", headers, body: JSON.stringify({ acceptedReplyLock: true }) }); if (!launch.espCampaignId) throw new Error("missing ESP id");
await json("/v1/dev/simulate-reply", { method: "POST", headers, body: JSON.stringify({ campaignId: campaign.id, fromEmail: "owned@example.com", bodyText: "Interested" }) }); const locked = await json(`/v1/campaigns/${campaign.id}/replies`, { headers }); if (!locked.replies[0]?.locked || locked.replies[0]?.bodyText) throw new Error("free reply leaked"); await json("/v1/dev/upgrade", { method: "POST", headers }); const unlocked = await json(`/v1/campaigns/${campaign.id}/replies`, { headers }); if (unlocked.replies[0]?.bodyText !== "Interested") throw new Error("Pro reply unavailable"); console.log("SMOKE PASS: research → resolve → real-path mock launch → locked reply → Pro unlock");
